sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: '000424'
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7pJsVcSJ8Wzpx7rYgc
    access-key-secret: UPQRui2Q9H8AJIpvsbxNXtQ3nD0NFp
    bucket-name: yuxun111
  redis:
    host: 192.168.181.128
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx4b8a3cfd66f49c75
    secret: 5351f2bb23714530ba2a229eac611b35